### ISSUE TITLE
Smart Doge Utility shows boxes when I enter new lines (Windows)

### ISSUE THREAD

**Issue by gurok** [ibispi/smart-doge-utility#1]
When I add a new line to the description of my task, Smart Doge Utility adds a box character before the new line. It's a proper character that I can go back and delete (pressing backspace).

**Comment by ibispi** [comment]
Issue noted, it will be fixed in the next commit. (^ ◕ᴥ◕ ^)/

**Comment by gurok** [comment]
Thank you!!!
